title: "Go言語ではじめるマイクラサーバー入門"
allow_override: true
summary: |-
  Go製のMinecraft: Bedrock Edition向けサーバーソフトウェアであるDragonfly(https://github.com/df-mc/dragonfly)の入門本です。
  ハンドブック的立ち位置でDragonflyの特徴から起動、機能拡張の手順を基礎から応用まで深く紹介。
topics:
  - "go"
  - "minecraft"
  - "bedrock"
  - "dragonfly"
published: false
price: 0
toc_depth: 2
chapters:
  - "at_first"
  - "what_is_dragonfly"
  - "lets_start"
  - "create_server"
  - "event_system"
  - "command_system"
  - "form_system"